### ISSUE TITLE
[BUG] : Toast Message Color Invisibility in White Mode

### ISSUE THREAD

**Issue by bj-jiwrajka** [SnowScriptWinterOfCode/Notes-App#14]
The toast message color is not clearly visible when the application is in white mode. This affects the overall user experience, making it difficult for users to read or notice the toast messages.

The toast message color should be visible and clearly distinguishable when the application is in white mode.

Screenshot:

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/97835955/01a93c5f-5225-4c22-9e1e-9d8fa4caef56)

**Comment by bj-jiwrajka** [comment]
@Nitya-Pasrija assign this to me:)

**Comment by nisha-laur** [comment]
Hi @bj-jiwrajka  
Thanks for raising the PR.

As per the code of conduct, you must get assigned to the issue before raising the PR.


From the next contributions, follow the flow.

**Comment by bj-jiwrajka** [comment]
> Hi @bj-jiwrajka Thanks for raising the PR.
> 
> As per the code of conduct, you must get assigned to the issue before raising the PR.
> 
> From the next contributions, follow the flow.

okay sure, I'll take care from next time:)
