### ISSUE TITLE
Feat: Adding a Search bar in the navbar

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/Notes-App#16]
I want to add a search bar in the navbar so that users can easily filter out their notes by typing the topic in the navbar.
Sample ss-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/99353300/8bc6c5bf-8450-4b91-820e-fbda2ad3f750)

**Comment by nisha-laur** [comment]
Hi @MonalikaPatnaik .Once you open a issue , it  becomes opened for anyone . Therefore while creating an issue . Do comment that you want that issue to be assigned to yourself.

**Comment by bj-jiwrajka** [comment]
you can assign this issue to me @nisha-laur
