### ISSUE TITLE
Alert message when the Title is empty

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/Notes-App#18]
To show an alert message when the title is empty and not saving the notes without title.Currently this alert is not being showed and the notes can be saved without title which can be avoided by showing the alert message.

![Screenshot 2023-12-30 135208](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/112767165/3cca7ada-53af-4f44-a19a-e12b0c681a97)

**Comment by ShaikArshidBanu** [comment]
@Nitya-Pasrija @nisha-laur please assign this issue to me.

**Comment by bj-jiwrajka** [comment]
> @Nitya-Pasrija @nisha-laur please assign this issue to me.

actually imo title should remain optional; sometimes we just need to add some notes without thinking much about what the title should be:)

**Comment by ShaikArshidBanu** [comment]
Adding Title can help us to search the saved notes easily in the further enhancement of website to obtain the notes by searching the saved notes with the hep of filter by giving title as input in case if we have a large number of notes it will be tedious to find out the specific notes :)

**Comment by bj-jiwrajka** [comment]
> Adding Title can help us to search the saved notes easily in the further enhancement of website to obtain the notes by searching the saved notes with the hep of filter by giving title as input in case if we have a large number of notes it will be tedious to find out the specific notes :)

okay cool:)

btw, we can further make it convenient for the user by adding a title by default with the first 2 words of the note, wouldn't it be great? solves both the issues. Now the user may or may not add a title and we can implement the said search feature easily.

**Comment by ShaikArshidBanu** [comment]
> > Adding Title can help us to search the saved notes easily in the further enhancement of website to obtain the notes by searching the saved notes with the hep of filter by giving title as input in case if we have a large number of notes it will be tedious to find out the specific notes :)
> 
> okay cool:)
> 
> btw, we can further make it convenient for the user by adding a title by default with the first 2 words of the note, wouldn't it be great? solves both the issues. Now the user may or may not add a title and we can implement the said search feature easily.

It would be better if this is given by the user itself for better remembering it during the time of searching specific notes.

**Comment by nisha-laur** [comment]
@ShaikArshidBanu Allow users the flexibility to choose whether they want to manually enter a title or use the suggested default.
Provide an option in the application settings or note creation interface for users to customize their title preferences.

**Comment by ShaikArshidBanu** [comment]
> @ShaikArshidBanu Allow users the flexibility to choose whether they want to manually enter a title or use the suggested default. Provide an option in the application settings or note creation interface for users to customize their title preferences.

@nisha-laur  I'll work upon this.
