### ISSUE TITLE
Add Application Images in the README.md file .

### ISSUE THREAD

**Issue by nisha-laur** [SnowScriptWinterOfCode/Notes-App#23]
Below Abstract Section , Create a section for Notes-App Images and add short  description .

**Comment by rajneesh069** [comment]
Can I work on this issue?

**Comment by nisha-laur** [comment]
Yeah , go ahead @rajneesh069

**Comment by rajneesh069** [comment]
@nisha-laur I've opened a few issues and have made the relevant code changes and attached the screenshots and videos to those issues, please look into them, as I would like to work on them.
