### ISSUE TITLE
[BUG]Theme switcher is not working properly.

### ISSUE THREAD

**Issue by rajneesh069** [SnowScriptWinterOfCode/Notes-App#31]
Problem:-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/aeb47471-0752-48c5-9337-e5a116595208)

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/e936d736-2e1d-4823-94f0-9c02ac541376)

Working Solution:-
Create a new theme.js file containing the logic of the theme slider. In the previous code, the problem was that the scripts were loaded after HTML  was parsed(even when they were inside the body at the end, the same is done using the defer tag inside the head tag of HTML). Then create a theme function inside it and call it obviously, then add another script tag with an "defer" attribute inside the head tag so that the script loads simultaneously with the DOM. And we'll need one more file named getInitialTheme which will get the initial theme from local storage and then give it to theme.js so that the initial theme can be loaded. That will be added inside a script tag with no attributes like defer or async so that it gets loaded as soon as the HTML is parsed!

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/7fffa250-3191-4e3a-83b4-7f24afdf7bae)

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/3f896f62-47ab-4000-b371-a10fced033d5)

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/2d36c12c-fb17-44fa-aab0-0a8596c3a0fe)

Effect:-

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/69e6576b-2ba7-487d-b41c-50ff0eeb2e42)

![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/8e5f9a77-ce6d-4f54-9624-fa285aa015ac)

https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/5274da09-3c7a-4826-a081-1e049922d496

I want to work on the issue if it gets approved.

**Comment by bj-jiwrajka** [comment]
Issue #8 already addresses this issue, so you can close yours:)

**Comment by rajneesh069** [comment]
Umm, are you still working on the fix? Actually I proposed a bit different kind of solution and that would add a feature of saving the mute state of the website.

**Comment by nisha-laur** [comment]
Issue #8 address the same issue and about the mute feature . I have already assigned it to you .

**Comment by hiirrxnn** [comment]
Can i be assigned this issue?
