### ISSUE TITLE
[Feature] Make the whole body's color change when dark theme is applied.

### ISSUE THREAD

**Issue by rajneesh069** [SnowScriptWinterOfCode/Notes-App#32]
Before :-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/e46e7d17-8f4c-4059-9d37-6d474ceb3118)

After :-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/ab84f2b1-7613-4b1f-abff-9de828c76a1a)

Code changes :-

Add the style="background: var(--color-secondary)" attribute to the body tag of index.html as well.
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/2de3b56b-b661-49a9-8d58-8d70e4e11ad5)

I want to work on the issue if the issue is approved.

**Comment by nisha-laur** [comment]
It does get changed .

**Comment by rajneesh069** [comment]
> It does get changed .

Hmm yesterday I pulled the changes so now it does get changed.
