### ISSUE TITLE
[BUG] Note Created Successfully alert not visible properly.

### ISSUE THREAD

**Issue by rajneesh069** [SnowScriptWinterOfCode/Notes-App#34]
Issue :-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/d33611bd-b8b7-41f5-a729-4a663edad670)
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/4e6817e8-28c1-4739-8f83-c9093fa14d7e)

Fix:-
Add color: var(--font-color); inside the styling property of the toast message, this way the font color will change accordingly. Also add the background: var(--color-secondary); inside the property so that the background of the toast message could change according to the theme changes. 
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/88ff05bc-f545-449b-ad09-b0ef5bc8c13c)

Effect:-
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/f7d70594-5a10-4fa9-a05f-4caaa0092468)
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/108251751/80025325-7156-4b71-a316-505b000bc29b)

I want to work on the issue if it gets approved.

**Comment by bj-jiwrajka** [comment]
Hey @rajneesh069 , issue #14 already addresses this issue and #15 fixes it too, so you can close your issue:)

**Comment by rajneesh069** [comment]
Oh Okay. Sure.
