### ISSUE TITLE
[FEAT]:Hover effect doesn't look good

### ISSUE THREAD

**Issue by iaayushmaan** [SnowScriptWinterOfCode/Notes-App#70]
**Feature request, description.**
The hover effect on the notes overlaps with other container, and this looks so odd.

**Describing the solution I like**
I would like to enhancethe hover effect with a more soothing transition, which includes 
-Adding a BoxShadow
-Adding Transition
-Scaling the div

**Before Enhancement**
![image](https://github.com/SnowScriptWinterOfCode/Notes-App/assets/116517217/fe0f04bf-d209-4e1e-a209-a1f33d65abf0)

**Assign this issue to me before I start working on the feat.**
@nisha-laur

**Comment by nisha-laur** [comment]
This issue has been handled already .
