### ISSUE TITLE
Display of a Confirmation Message Before Note Deletion

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/Notes-App#76]
Prior to initiating the deletion of a note, the app will provide the user with a warning asking 'Are you sure you want to delete this note?' This serves as a gentle reminder, ensuring that the user confirms their intention to delete the note.

Please assign it to me @nisha-laur @Nitya-Pasrija

**Comment by avanimathur** [comment]
@nisha-laur @Nitya-Pasrija

**Comment by PranjaliBhardwaj** [comment]
Assign this issue to me, I can complete this  by HTML and Javascript.

**Comment by PranjaliBhardwaj** [comment]
@ayushichoudhary-19 @Nitya-Pasrija
